spring:
  application:
    name: love-ai-agent
  profiles:
    active: prod
  ai:
    dashscope: # 引入的哪种系列大模型
      chat:
        options:
          model: qwen-plus

    vectorstore:
      pgvector:
        dimensions: 1536
        index-type: hnsw
        distance-type: cosine_distance
        max-document-batch-size: 10000
#    mcp:
#      client:
#        #        sse:
#        #          connections:
#        #            server1:
#        #              url: http://localhost:8127
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.figgo.loveaiagent.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


